version: '3.7'

services:
###> symfony/mailer ###
  mailer:
    image: tophfr/mailcatcher
    expose:
      - 80
    networks:
      - pimties
      - hostmanager
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{mailer}.rule=Host(`mail.pimties.localhost`)"
      - "traefik.http.routers.{mailer}.tls=true"
###< symfony/mailer ###
