version: "3.7"
services:
  mysql:
    image: mysql:8-debian
    networks:
      - pimties
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql:/etc/mysql/conf.d
    env_file:
      - db.env

  node:
    image: node:19
    working_dir: /srv
    volumes:
      - ./:/srv/

  php:
    build: ./docker/php
    env_file:
      - docker.env
      - db.env
    networks:
      - pimties
    volumes:
      - $SSH_AUTH_SOCK:/tmp/agent.sock
      - ~/.composer:/home/.composer
      - ./docker/config/bashrc:/home/.bashrc
      - ./docker/config/bash_aliases:/home/.bash_aliases
      - ./docker/config/inputrc:/home/.inputrc
      - ./docker/data/history:/home/.bash_history
      - ./:/srv/

  nginx:
    image: nginx:1.15.9-alpine
    networks:
      - pimties
      - hostmanager
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{nginx}.rule=Host(`pimties.localhost`)"
      - "traefik.http.routers.{nginx}.tls=true"
    expose:
      - 443
    depends_on:
      - php
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/srv/:ro

networks:
  pimties:
    name: pimties
    external: false
  hostmanager:
    external: true

volumes:
  db: ~